- framework/framework.go
It should expose an interface and validate at runtime, so that if
statements can be used in the invoking main function. For example:
if isHTTP() {
framework.RegisterHTTPFunction("/", fn.HelloWorld)
} else {
framework.RegisterEventFunction("/", fn.HelloWorld)
}
won't compile for all possible inputs unless both Register*Function
types expose and interface{} and validate later.
> Update RegisterHTTPFunction signature

- framework/framework.go
BEFORE:
Error while converting event data: json: cannot unmarshal object into Go struct field test.data of type string
AFTER:
Error: json: cannot unmarshal object into Go struct field test.data of type string, while converting event data: {"data": test"}
> Improve error message reporting for event functions

- framework/framework.go
Before:
```go
error parsing legacy cloud event: json: cannot unmarshal number into Go struct field Resource.resource.type of type string
```
After:
```go
Error: json: cannot unmarshal number into Go struct field Resource.resource.type of type string, parsing legacy cloud event: {
"resource": {
"service": "pubsub.googleapis.com",
"named": "mytopic",
"type": 12
},
"data": {
"@type": "type.googleapis.com/google.pubsub.v1.PubsubMessage",
"attributes": null,
"data": "test data"
}
}
```
> Improve logging

- README.md
- funcframework/framework.go
- funcframework/framework_test.go
The less generic package name is much preferred.
This is done in two parts. This commit adds the new package, and the
next will remove the old. The transition is done this way to faciliate
the migration to the new package name internally.
> Update package name to funcframework

- funcframework/framework.go
> Only flush logs after HTTP execution if GCF env vars are set

- .github/workflows/conformance.yml
- set_up_conformance_tests.sh
- testdata/conformance/cmd/cloudevent/main.go
- testdata/conformance/cmd/http/main.go
- testdata/conformance/cmd/legacyevent/main.go
- testdata/conformance/function/function.go
- testdata/go.mod
Running them without buildpacks is more hermetic, faster, and easier
to emulate locally.
> Run conformance tests without buildpacks

- .github/workflows/conformance.yml
Need to use GitHub Actions syntax instead of Circle CI syntax.
If there's an error in the GitHub Actions config file, GitHub just skips the Action...
Also, pre-install the conformance test client so that it doesn't count against the first conformance test's `startDelay` during `go run`.
Before:
After:
You can see the conformance client is immediately "found" at the start of the HTTP test and no extra go modules have to be downloaded.
> Fix conformance tests configuration

- .github/release-please.yml
Sets up simple release please for simple release notes. (To be generated)
Fixes: https://github.com/GoogleCloudPlatform/functions-framework-go/issues/76
CI failure is unrelated.
---
Simple:
- https://github.com/googleapis/google-api-go-client/blob/master/.github/release-please.yml
Not sure if we should have a more complicated release like:
- https://github.com/googleapis/google-cloud-go/blob/master/.github/workflows/release.yaml
CC: @codyoss
> chore: add simple release setup for golang functions framework

- funcframework/framework.go
- funcframework/framework_test.go
- functions/functions.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- testdata/conformance/function/function.go
This separates the encouraged, declarative function signature API away
from the `funcframework` package, which should primarily be used for local testing going forward.
```go
package fn
import (
"fmt"
"github.com/GoogleCloudPlatform/functions-framework-go/functions"
)
func init() {
functions.HTTP("declarativeHTTP", myHTTPFunc)
functions.CloudEvent("declarativeCloudEvent", myCloudEventFunc)
}
func myHTTPFunc(w http.ResponseWriter, r *http.Request) {
fmt.Println("HTTP function")
}
func myCloudEventFunc(ctx context.Context, ce cloudevents.Event) error {
fmt.Println("CloudEvent function")
return nil
}
```
Also, refactor some of the internal/registry implementation so it's more
obvious that `functions` package and `funcframework` package are sharing
the same registry.
> feat: move declarative function API into `functions` package

- README.md
The current CloudEvent example does not work:
```
❯ go run cmd/main.go
./functions.go:12:41: undefined: cloudEvent
```
> docs: fix CloudEvent example

- .github/release-please.yml
- .github/workflows/release-please.yml
This is the recommended way to configure
[release-please](https://github.com/googleapis/release-please#setting-up-release-please)
and allows running additional steps before/after for validation.
> chore: use release please GitHub Action

- testdata/conformance/function/prerun.sh
Use a template `go.mod` instead of running `go mod tidy` so that the
version of Go on the machine running `prerun.sh`  does not impact the `go.mod` that gets
generated.
When building the resulting function source code with `pack`, the
version of Go actually used to build will be depedent on the builder
image used.
> chore: fix prerun.sh to work with all Go versions

- .github/release-please.yml
- .github/workflows/buildpack-integration-test.yml
Go back to using the GitHub App version because the GitHub Action's bot
doesn't have Google CLA.
> chore: fix release please

- .github/workflows/conformance.yml
- .github/workflows/lint.yml
- .github/workflows/unit.yml
- Test 1.18
- Remove older versions that aren't used, as our matrix is large.
> ci: test go118

- funcframework/framework.go
- funcframework/framework_test.go
CloudEvent functions currently return 500 when an error is returned, but
do not do anything with the error message. This logs the error message
to stderr so it is not lost.
Unlike Background Functions, the error message is NOT included in the
response body though.
Also, add fields for checking stderr to the unit tests.
> fix: log CloudEvent function errors to stderr

- funcframework/framework.go
- funcframework/framework_test.go
- internal/registry/registry.go
- internal/registry/registry_test.go
There are two ways to test multiple functions within one server. 
1. Declaratively register multiple functions (e.g. calling `functions.HTTP()`) and run `go run cmd/main.go` without setting the env var `FUNCTION_TARGET`. In this case, all registered functions will be served  at "/{func_name}".
2. Manually register the handers (e.g. calling `funcframework.RegisterHTTPFunctionContext()`)  and run `go run cmd/main.go` without setting the env var `FUNCTION_TARGET`. In this case, only the registered handlers will be served at the user defined path.
Closes #109
> fix: Allow registering multiple functions with one server for local testing.

- funcframework/framework.go
These blank lines were included to force-flush logs on previous versions of GCF, but are no longer needed because there have been changes to GCF log handling since then.
> fix: remove obsolete blank prints

- .github/workflows/conformance.yml
- testdata/conformance/function/function.go
Checks that the Functions Framework can handle concurrent requests
Also, refactor the conformance test GitHub Action to call install the client in a separate GitHub Job/Runner so that the Go version being used for the test doesn't matter. And call the client directly the same way one would locally test.
> chore: turn on concurrency conformance test

- .github/workflows/conformance.yml
Interestingly, this did not cause a failure.
> chore: fix parameter name in conformance action

- funcframework/framework.go
- funcframework/framework_test.go
- functions/functions.go
- internal/registry/registry.go
- internal/registry/registry_test.go
There are two ways to test multiple functions within one server. 
1. Declaratively register multiple functions (e.g. calling `functions.HTTP()`) and run `go run cmd/main.go` without setting the env var `FUNCTION_TARGET`. In this case, all registered functions will be served  at "/{func_name}".
2. Manually register the handers (e.g. calling `funcframework.RegisterHTTPFunctionContext()`)  and run `go run cmd/main.go` without setting the env var `FUNCTION_TARGET`. In this case,  the registered handlers will be served at the user defined path.
Closes #109
> feat: Allow registering multiple functions with one server for local testing

- funcframework/framework.go
This reverts commit 5c7091f.
This logging is still important to ensure logs without newlines are flushed at the end of every request.
> Revert "fix: remove obsolete blank prints (GoogleCloudPlatform#144)"

- funcframework/framework.go
- funcframework/framework_test.go
- functions/functions.go
- internal/registry/registry.go
Add a new signature in functions framework that will support strongly typed objects. This signature will take a strong type T as an input and can return a strong type T, built in types, None and/or error as an output.
Sample declarations:
`func helloWorld(s T) (T, error) `
`func helloWorld(s T1) (T2, error) `
`func helloWorld(s T1)`
`func helloWorld(s T1) error`
> feat: Add support for strongly typed function signature

- funcframework/framework.go
Wrap panic message so it appears as one entry in cloud logging.
> fix: wrap panic message when log to stderr

- funcframework/framework.go
Seems like somehow, with a single added new line, we log to cloud logging in multiple entries instead of one. This attempts to fix that.
> fix: attempt to log panic error in one logging entry

- funcframework/framework.go
Fixes framework's status print "Serving function: ..." on startup when no target is specified in local dev (allows serving multiple functions from a single instance of function framework). Today the output looks like:
```
Serving function: "declarativeHTTP"Serving function: "concurrentHTTP"Serving function: "declarativeCloudEvent"
```
With the fix:
```
Serving function: "declarativeHTTP"
Serving function: "concurrentHTTP"
Serving function: "declarativeCloudEvent"
```
> fix: correct formatting of status print

- .github/workflows/codeql.yml
- .github/workflows/conformance.yml
- .github/workflows/lint.yml
- .github/workflows/scorecard.yml
- .github/workflows/unit.yml
This PR updates `step-security/harden-runner` from 2.5.0 to 2.5.1 in the GitHub Actions workflows.
GitHub Actions recently started making outbound calls to a few endpoints not in the default allowed list.   This causes the build to get stuck when using a `block` policy with `harden-runner`. This update to harden-runner (version v2.5.1), adds these new endpoints to the default allowed list. 
Release notes for the latest version are here:
https://github.com/step-security/harden-runner/releases/tag/v2.5.1
@kenneth-rosario
> ci: update harden-runner

- .github/workflows/unit.yml
- go matrix updates
Update the go matrix in the CI workflows to include the new supported runtimes.
Auto-generated by https://github.com/chizhg/serverless-runtimes-automation/actions/runs/5901430748
> ci: [Automation] Update go matrix

- README.md
- funcframework/logging.go
- funcframework/logging_test.go
This is a small improvement to https://github.com/GoogleCloudPlatform/functions-framework-go/pull/246
Match the behavior of executionId with other runtimes e.g. nodeJs.
> fix: Generate psedurandom execution id if Function-Execution-Id is not provided; Update README with examples
